pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}

rootProject.name = 'ClientSideCrystalsUniversal'

include 'bundle'
include 'mc121', 'mc1211', 'mc1212', 'mc1213', 'mc1214', 'mc1215'
include 'mc1216', 'mc1217', 'mc1218', 'mc1219', 'mc12110', 'mc12111'
include 'mc261', 'mc2611', 'mc2612', 'mc262'
